server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
      - id: userModule
        uri: http://localhost:8083/
        predicates:
        - Path=/users/**
      - id: employeeModule
        uri: http://localhost:8084/
        predicates:
        - Path=/employees/**


